### ISSUE TITLE
Don't get Spawn Egg when break spawner

### ISSUE THREAD

**Issue by joshuaepstein** [Iskallia/iSpawner#1]
If I break the spawner with Spawn Eggs left in the spawner slot, I do not get the spawn eggs back.

Expected behaviour:
The Spawner to drop the spawn eggs.

**Comment by KaptainWutax** [comment]
Eggs aren't supposed to drop, but I can certainly make the tile entity data persist in the item stack.

**Comment by joshuaepstein** [comment]
Thanks. That would help me losing eggs in VH...
